name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: purescript-contrib/setup-purescript@main

      - uses: actions/setup-node@v1
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          apt install chezscheme
          npm install spago@next

      - name: Build source
        run: npm run build

      - name: Run tests
        run: |
          npm run test
