name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          sudo apt install chezscheme

      - name: Setup PureScript dependencies
        run: npm i --global purescript@0.15.10 purs-tidy@latest spago@next purescript-psa@latest

      - name: Build source
        run: npm run build

      - name: Run tests
        run: |
          npm run test
